# -*- coding: utf-8 -*-
"""01-leitura-e-escrita-de-arquivos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/rdzw/9d74274378cec82677f44aee39eb1f45/01-leitura-e-escrita-de-arquivos.ipynb
"""

# importando a biblioteca 05 - Pandas
import pandas as pd

# lendo arquivo csv
df = pd.read_csv('meu_arquivo.csv', encoding='latin1', sep=';')

df

# Lendo arquivos HTML
tabela_wiki = pd.read_html('https://en.wikipedia.org/wiki/Minnesota')

print(f'Total de tabelas {len(tabela_wiki)}')

tabela_wiki_temperatura = pd.read_html('https://en.wikipedia.org/wiki/Minnesota', match='Average daily maximum and minimum temperatures for selected cities in Minnesota')

tabela_wiki_temperatura[0]

#Criando um DataFrame a partir de uma lista

# criando uma lista de dados
dados = [[1, 'João', 'São Paulo'], [2, 'Maria', 'Rio de Janeiro'], [3, 'José', 'Belo Horizonte']]

# criando um DataFrame a partir da lista
df = pd.DataFrame(dados, columns=['id', 'nome', 'cidade'])


df

#Criando um DataFrame a partir de um dicionário:

# criando um dicionário de dados
dados = {'id': [1, 2, 3], 'nome': ['João', 'Maria', 'José'], 'cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte']}

# criando um DataFrame a partir do dicionário
df = pd.DataFrame(dados)

df.head()

#Criando um DataFrame a partir de uma lista de dicionários:

# criando uma lista de dicionários
dados = [{'id': 1, 'nome': 'João', 'cidade': 'São Paulo'}, {'id': 2, 'nome': 'Maria', 'cidade': 'Rio de Janeiro'}, {'id': 3, 'nome': 'José', 'cidade': 'Belo Horizonte'}]

# criando um DataFrame a partir da lista de dicionários
df = pd.DataFrame(dados)


df.head()

# escrevendo um DataFrame em um arquivo CSV
df.to_csv('novo_arquivo_1.csv', index=False, encoding = 'latin1')

# escrevendo um DataFrame em um arquivo Excel
df.to_excel('novo_arquivo_1.xlsx', index=False, encoding = 'latin1')